local keymap = vim.keymap.set
local opts = { noremap = true, silent = true }
keymap("i", "jk", "<Esc>", opts)
keymap("i", "jK", "<Esc>", opts)
keymap("i", "JK", "<Esc>", opts)
keymap("i", "Jk", "<Esc>", opts)
keymap("n", "H", "^", opts)
keymap("n", "L", "$", opts)
keymap("v", "H", "^", opts)
keymap("v", "L", "$", opts)
keymap("n", "<Leader>o", "o<Esc>", opts)
keymap("n", "<Leader>O", "O<Esc>", opts)
keymap("n", "<Leader>C", "v^c", opts)
keymap("n", "<Leader>S", "v^s", opts)
keymap("n", "<Leader>D", "v^d", opts)
keymap("n", "<Leader>V", "v^", opts)
keymap("t", "<Esc><Esc>", "<C-\\><C-n>")
keymap("n", "J", "10jzz", opts)
keymap("n", "K", "10kzz", opts)
keymap("v", "J", "10jzz", opts)
keymap("v", "K", "10kzz", opts)
keymap("n", "j", "gj", opts)
keymap("n", "k", "gk", opts)
keymap("n", "ya", ":%y<CR>", opts)
keymap("v", "v", "<C-v>", opts)
keymap("n", "<Tab>", "<Nop>", opts)
keymap("n", "<C-i>", "<Nop>", opts)
keymap("n", "<Esc><Esc>", "<Cmd>noh<CR>", opts)
