# Path to the test file (Liquid template)
#
# Variables:
#
# - `manifest_dir`: Package directory
# - `contest`:      Contest ID (e.g. "abc100")
# - `bin_name`:     Name of a `bin` target (e.g. "abc100-a")
# - `bin_alias`:    "Alias" for a `bin` target defined in `pacakge.metadata.cargo-compete` (e.g. "a")
# - `problem`:      Alias for `bin_alias` (deprecated)
#
# Additional filters:
#
# - `kebabcase`: Convert to kebab case (by using the `heck` crate)
test-suite = "{{ manifest_dir }}/testcases/{{ bin_alias }}.yml"

[template]
src = '''
__PROCON_TEMPLATE_RS__
'''

[template.new]
# `edition` for `Cargo.toml`.
edition = "2021"
# `profile` for `Cargo.toml`.
#
# By setting this, you can run tests with `opt-level=3` while enabling `debug-assertions` and `overflow-checks`.
#profile = '''
#[dev]
#opt-level = 3
#'''
dependencies = '''
ac-library-rs = "0.2.0"
itertools = "0.14.0"
num = "0.4.3"
num-bigint = "0.4.6"
num-decimal = "0.2.5"
num-traits = "0.2.19"
num-integer = "0.1.46"
proconio = { version = "0.5.0", features = ["derive"] }
rust_decimal = "1.34.3"
superslice = "1.0.0"
regex = "1.10.4"
ordered-float = "5.0.0"
easy-ext = "1.0.2"
rand = "0.9.2"
rand_pcg = "0.9.0"
nalgebra = "0.30.0"
'''

[template.new.copy-files]
"./template-cargo-lock.toml" = "Cargo.lock"

[new]
kind = "cargo-compete"
# Platform
# - atcoder
# - codeforces
# - yukicoder
platform = "atcoder"
# Path (Liquid template)
#
# Variables:
#
# - `contest`:      Contest ID. **May be nil**
# - `package_name`: Package name
path = "./{{ contest }}"


[test]
# Toolchain for the test. (optional)
toolchain = "1.89.0"
# Profile for `cargo build`. ("dev" | "release")
#
# Defaults to `"dev"`.
#profile = "dev"

[submit]
kind = "file"
path = "{{ src_path }}"
language_id = "6088"
