name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  checks:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: NixOS-WSL
            os: ubuntu-latest
            just: ci-nixos
          - name: macOS nix-darwin
            os: macos-latest
            just: ci-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run checks
        run: nix develop -c just ${{ matrix.just }}
